module.exports={

cat00 :[
  {label: 'Action song Eng', value: 'Action song Eng' },
  {label: 'Action song Mal', value: 'Action song Mal' },
  {label: 'Clay modelling', value: 'Clay modelling' },
  {label: 'Colouring crayon', value: 'Colouring crayon' },
   {label: 'Pencil drawing', value: 'Pencil drawing' },
   {label: 'Story telling Eng', value: 'Story telling Eng' },
   {label: 'Story telling mal', value: 'Story telling mal' },
   {label: 'Show & Tell', value: 'Show & Tell' },
   {label: 'Memory Retention', value: 'Memory Retention' },
   {label: 'Folk dance', value: 'Folk dance' },
],


cat0 : [
  {label: 'Clay modelling', value: 'Clay modelling' },
  {label: 'Colouring crayon', value: 'Colouring crayon' },
  {label: 'Light music', value: 'Light music' },
  {label: 'Memory Retention', value: 'Memory Retention' },
    {label: 'Pencil drawing', value: 'Pencil drawing' },
    {label: 'Story telling Eng', value: 'Story telling Eng' },
    {label: 'Story telling mal', value: 'Story telling mal' },
    {label: 'Recitation Eng', value: 'Recitation Eng' },
    {label: 'Recitation Mal', value: 'Recitation Mal' },
    {label: 'Show & Tell', value: 'Show & Tell' },
    {label: 'Folk dance', value: 'Folk dance' },
  ],


cat1 : [
  {label: 'Pencil drawing', value: 'Pencil drawing' },
  {label: 'Painting crayon', value: 'Painting crayon' },
  {label: 'Painting Water colour', value: 'Painting Water colour' },
  {label: 'Light music', value: 'Light music' },
  {label: 'Recitation Eng', value: 'Recitation Eng' },
  {label: 'Recitation Mal', value: 'Recitation Mal' },
  {label: 'Recitation Hin', value: 'Recitation Hin' },
  {label: 'Elocution Eng', value: 'Elocution Eng' },
  {label: 'Elocution Mal', value: 'Elocution Mal' },
  {label: 'Folkdance (common)', value: 'Folkdance (common)' },
  {label: 'News Reading Eng', value: 'News Reading Eng' },
  {label: 'news Reading Mal', value: 'news Reading Mal' },
  {label: 'News Reading Hindi', value: 'News Reading Hindi' },
  {label: 'Hand writing Eng', value: 'Hand writing Eng' },
  {label: 'Hand writing Mal', value: 'Hand writing Mal' },
  {label: 'Hand writing Hindi', value: 'Hand writing Hindi' },
  ],
  


  cat2 : [
    {label: 'Pencil drawing', value: 'Pencil drawing' },
    {label: 'Painting Water colour', value: 'Painting Water colour' },
    {label: 'Cartoon', value: 'Cartoon' },
    {label: 'Essay writing Eng', value: 'Essay writing Eng' },
    {label: 'Essay writing Mal', value: 'Essay writing Mal' },
    {label: 'Poetry writing Eng', value: 'Poetry writing Eng' },
    {label: 'Poetry writing Mal', value: 'Poetry writing Mal' },
    {label: 'Story writing Eng', value: 'Story writing Eng' },
    {label: 'Story writing Mal', value: 'Story writing Mal' },
    {label: 'Light music boys', value: 'Light music boys' },
    {label: 'Light music girls', value: 'Light music girls' },
    {label: 'Recitation Eng', value: 'Recitation Eng' },
    {label: 'Recitation Mal', value: 'Recitation Mal' },
    {label: 'Recitation Hin', value: 'Recitation Hin' },
    {label: 'Recitation Arabic', value: 'Recitation Arabic' },
    {label: 'Recitation Sanskrit', value: 'Recitation Sanskrit' },
    {label: 'Elocution Eng', value: 'Elocution Eng' },
    {label: 'Elocution Mal', value: 'Elocution Mal' },
    {label: 'Elocution Hindi', value: 'Elocution Hindi' },
   {label: 'Folkdance girls', value: 'Folkdance girls' },
   {label: 'Folkdance boys', value: 'Folkdance boys' },
   {label: 'Bharatanatyam Boy', value: 'Bharatanatyam Boy' },
   {label: 'Bharathamatyam Girls', value: 'Bharathamatyam Girls' },
   {label: 'Mohiniyattom', value: 'Mohiniyattom' },
   {label: 'Monoact (Common)', value: 'Monoact (Common)' },
   {label: 'News Reading Eng', value: 'News Reading Eng' },
  {label: 'news Reading Mal', value: 'news Reading Mal' },
  {label: 'News Reading Hindi', value: 'News Reading Hindi' },
  {label: ' classical music', value: ' classical music' },
  {label: ' Translation Eng', value: ' Translation Eng' },
  {label: ' Translation Mal', value: ' Translation Mal' },
  {label: ' Translation Hindi', value: ' Translation Hindi' },

  ],
 
  

  cat3 : [
    {label: 'Pencil drawing', value: 'Pencil drawing' },
    {label: 'Painting Water colour', value: 'Painting Water colour' },
    {label: 'Painting oil colour', value: 'Painting oil colour' },
    {label: 'Cartoon', value:'Cartoon' },
    {label: 'Poster Designing', value: 'Poster Designing' },
    {label: 'Collage', value: 'Collage' },
    {label: 'Essay writing Eng', value: 'Essay writing Eng' },
    {label: 'Essay writing Mal', value: 'Essay writing Mal' },
    {label: 'Essay writing Hin', value: 'Essay writing Hin' },
    {label: 'Poetry writing Eng', value: 'Poetry writing Eng' },
    {label: 'Poetry writing Mal', value: 'Poetry writing Mal' },
    {label: 'Poetry writing Hin', value: 'Poetry writing Hin' },
   {label: 'Story writing Eng', value: 'Story writing Eng' },
   {label: 'Story writing Mal', value: 'Story writing Mal' },
   {label: 'Story writing Hin', value: 'Story writing Hin' },
   {label: 'Light music boys', value: 'Light music boys' },
   {label: 'Light music girls', value: 'Light music girls' },
   {label: 'Mappilappattu boys', value: 'Mappilappattu boys' },
   {label: 'Mappilappattu girls', value: 'Mappilappattu girls' },
   {label: 'Recitation Eng', value: 'Recitation Eng' },
   {label: 'Recitation Mal', value: 'Recitation Mal' },
   {label: 'Recitation Hin', value: 'Recitation Hin' },
   {label: 'Recitation Arabic', value: 'Recitation Arabic' },
   {label: 'Recitation Sanskrit', value: 'Recitation Sanskrit' },
   {label: 'Extempore Eng', value: 'Extempore Eng' },
   {label: 'Extempore Mal', value: 'Extempore Mal' },
   {label: 'Extempore Hindi', value: 'Extempore Hindi' },
   {label: 'Folkdance girls', value: 'Folkdance girls' },
   {label: 'Folkdance boys', value: 'Folkdance boys' },
   {label: 'Bharatanatyam Boy', value: 'Bharatanatyam Boy' },
   {label: 'Bharathamatyam Girls', value: 'Bharathamatyam Girls' },
   {label: 'Kuchipudi boy', value: 'Kuchipudi boy' },
   {label: 'Kuchipudi girls', value: 'Kuchipudi girls' },
   {label: 'Mohiniyattom', value: 'Mohiniyattom' },
   {label: 'Mimicry (Common)', value: 'Mimicry (Common)' },
   {label: 'Monoact (Common)', value: 'Monoact (Common)' },
   {label: 'Classical music boy', value: 'Classical music boy' },
   {label: 'Classical music girl', value: 'Classical music girl' },
   {label: 'Instrumental music', value: 'Instrumental music' },
   {label: 'Tabala', value: 'Tabala' },
   {label: 'Mrudangam', value: 'Mrudangam' },
   {label: 'Guitar', value: 'Guitar' },
   {label: 'Flute', value: 'Flute' },
   {label: 'Violin (eastern)', value: 'Violin (eastern)' },
   {label: 'News Writing English', value: 'News Writing English' },
   {label: 'News Writing Mal', value: 'News Writing Mal' },
   {label: 'News writing Hindi', value: 'News writing Hindi' },
   {label: 'Blog writing Eng', value: 'Blog writing Eng' },
   {label: 'Blog writing Mal', value: 'Blog writing Mal' },
   {label: 'Blog writing Hindi', value: 'Blog writing Hindi' },
  ],


   cat4 : [
        {label: 'Pencil drawing', value: 'Pencil drawing' },
    {label: 'Painting Water colour', value: 'Painting Water colour' },
    {label: 'Painting oil colour', value: 'Painting oil colour' },
    {label: 'Cartoon', value:'Cartoon' },
    {label: 'Poster Designing', value: 'Poster Designing' },
    {label: 'Collage', value: 'Collage' },
    {label: 'Essay writing Eng', value: 'Essay writing Eng' },
    {label: 'Essay writing Mal', value: 'Essay writing Mal' },
    {label: 'Essay writing Hin', value: 'Essay writing Hin' },
    {label: 'Poetry writing Eng', value: 'Poetry writing Eng' },
    {label: 'Poetry writing Mal', value: 'Poetry writing Mal' },
    {label: 'Poetry writing Hin', value: 'Poetry writing Hin' },
   {label: 'Story writing Eng', value: 'Story writing Eng' },
   {label: 'Story writing Mal', value: 'Story writing Mal' },
   {label: 'Story writing Hin', value: 'Story writing Hin' },
   {label: 'Light music boys', value: 'Light music boys' },
   {label: 'Light music girls', value: 'Light music girls' },
   {label: 'Mappilappattu boys', value: 'Mappilappattu boys' },
   {label: 'Mappilappattu girls', value: 'Mappilappattu girls' },
   {label: 'Recitation Eng', value: 'Recitation Eng' },
   {label: 'Recitation Mal', value: 'Recitation Mal' },
   {label: 'Recitation Hin', value: 'Recitation Hin' },
   {label: 'Recitation Arabic', value: 'Recitation Arabic' },
   {label: 'Recitation Sanskrit', value: 'Recitation Sanskrit' },
   {label: 'Extempore Eng', value: 'Extempore Eng' },
   {label: 'Extempore Mal', value: 'Extempore Mal' },
   {label: 'Extempore Hindi', value: 'Extempore Hindi' },
   {label: 'Folkdance girls', value: 'Folkdance girls' },
   {label: 'Folkdance boys', value: 'Folkdance boys' },
   {label: 'Bharatanatyam Boy', value: 'Bharatanatyam Boy' },
   {label: 'Bharathamatyam Girls', value: 'Bharathamatyam Girls' },
   {label: 'Kuchipudi boy', value: 'Kuchipudi boy' },
   {label: 'Kuchipudi girls', value: 'Kuchipudi girls' },
   {label: 'Mohiniyattom', value: 'Mohiniyattom' },
   {label: 'Mimicry (Common)', value: 'Mimicry (Common)' },
   {label: 'Monoact (Common)', value: 'Monoact (Common)' },
   {label: 'Classical music boy', value: 'Classical music boy' },
   {label: 'Classical music girl', value: 'Classical music girl' },
   {label: 'Instrumental music', value: 'Instrumental music' },
   {label: 'Tabala', value: 'Tabala' },
   {label: 'Mrudangam', value: 'Mrudangam' },
   {label: 'Guitar', value: 'Guitar' },
   {label: 'Flute', value: 'Flute' },
   {label: 'Violin (eastern)', value: 'Violin (eastern)' },
   {label: 'News Writing English', value: 'News Writing English' },
   {label: 'News Writing Mal', value: 'News Writing Mal' },
   {label: 'News writing Hindi', value: 'News writing Hindi' },
   {label: 'Blog writing Eng', value: 'Blog writing Eng' },
   {label: 'Blog writing Mal', value: 'Blog writing Mal' },
   {label: 'Blog writing Hindi', value: 'Blog writing Hindi' },
  ]
}
